### ISSUE TITLE
`case_insensitive_keys` returns nil

### ISSUE THREAD

**Issue by stephanvane** [mcordell/grape_token_auth#37]
When I put

```ruby
include GrapeTokenAuth::ActiveRecord::TokenAuth
```

In my User model, the `case_insensitive_keys` method returns nil (which breaks everything)

**Without** `include GrapeTokenAuth::ActiveRecord::TokenAuth`

```
[1] pry(main)> User.case_insensitive_keys
=> [:email]
```

**With** `include GrapeTokenAuth::ActiveRecord::TokenAuth`

```
[1] pry(main)> User.case_insensitive_keys
=> nil
```

Any suggestions?

**Comment by mcordell** [comment]
This is because this  line https://github.com/mcordell/grape_token_auth/blob/master/lib/grape_token_auth/orm_integrations/active_record_token_auth.rb#L62

clobbers Devise's `case_insensitive_keys` here is a possible fix:

https://github.com/mcordell/grape_token_auth/tree/devise-clobber-fix

However, you are likely to run into more problems like this because this gem is not meant to be run concurrently with devise & rails. If you are interested in running rails/devise, you might have a look at my other repo: https://github.com/mcordell/grape_devise_token_auth

Which is a compatibility layer between `devise_token_auth` and `grape`.

**Comment by stephanvane** [comment]
Hi, sorry for the late reply. Thanks for having a look at this.

Unfortunately, this fix only works when the `include GrapeTokenAuth::ActiveRecord::TokenAuth` line is place **below** the `devise :database_authenticatable,....` line. Device defines the `case_insensitive_keys` method, so the new `unless` checks won't have any effect if device is included later on.

At the moment I work around this issue by placing the following line in my `user.rb`
```ruby
@case_insensitive_keys = [:email]
```
But this isn't really a good, long term, solution of course.

**Comment by evserykh** [comment]
```ruby
class User < ActiveRecord::Base
  ...
  include GrapeTokenAuth::ActiveRecord::TokenAuth

  devise :database_authenticatable, :registerable, :recoverable, 
         :rememberable, :trackable, :confirmable,
         case_insensitive_keys: [:email] 
end
```

works for me but it's also not a very good solution I guess

**Comment by mcordell** [comment]
I just pushed a new fix to the 'devise-clobber-fix' branch, can someone confirm that it works?

**Comment by mcordell** [comment]
Merged, re-open if this persists
